
addons:
  sonarcloud:
    organization: "ramona484"
    token: $SONAR_TOKEN

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

matrix:
  include:
    - language: python
      before_install:
        - echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc

      before_script:
        - pip install ci_secrets
      script:
      #If this is the first commit on a branch, use 0000000000000000000000000000000000000000 to match the behavior of GitLab CI.
        - export COMMIT_RANGE=${TRAVIS_COMMIT_RANGE:-"0000000000000000000000000000000000000000"}
        - export LAST_COMMIT=${COMMIT_RANGE%%.*}
        - ci_secrets --since $LAST_COMMIT --includesMergeCommit --log INFO

    - language: node_js
      node_js:
         - "14"
      sudo: required
      dist: trusty

      services:
         - docker

      before_install:
         - docker build -t trivy-ci-test:${COMMIT} .
         - export VERSION=$(curl --silent "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
         - wget https://github.com/aquasecurity/trivy/releases/download/v${VERSION}/trivy_${VERSION}_Linux-64bit.tar.gz
         - tar zxvf trivy_${VERSION}_Linux-64bit.tar.gz
         - docker build -t dockle-ci-test:${COMMIT} .
         - export VERSION=$(curl --silent "https://api.github.com/repos/goodwithtech/dockle/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
         - wget https://github.com/goodwithtech/dockle/releases/download/v${VERSION}/dockle_${VERSION}_Linux-64bit.tar.gz
         - tar zxvf dockle_${VERSION}_Linux-64bit.tar.gz

      before_script:
         - npm install
      script:
         - docker build -t tree-shop .
         - sonar-scanner
         - ./trivy --exit-code 0 --severity HIGH --no-progress trivy-ci-test:${COMMIT}
         - ./trivy --exit-code 1 --severity CRITICAL --no-progress trivy-ci-test:${COMMIT}
         - ./dockle --exit-code 1 dockle-ci-test:${COMMIT}

      after_success:
         - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
         - docker tag tree-shop $DOCKER_USER/tree-shop:$TRAVIS_BUILD_NUMBER
         - docker push $DOCKER_USER/tree-shop:$TRAVIS_BUILD_NUMBER
         - docker tag tree-shop $DOCKER_USER/tree-shop:latest
         - docker push $DOCKER_USER/tree-shop:latest

      cache:
         directories:
           - $HOME/.cache/trivy
