
version: 2.1

executors:
  docker-publisher:
    environment:
      IMAGE_NAME: ramona84/tree-shop
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:

  dockle:
     docker:
      - image: docker:18.09-git
     steps:
       - checkout
       - setup_remote_docker
       - run:
           name: Build image
           command: docker build -t dockle-ci-test:${CIRCLE_SHA1} .
       - run:
           name: Install dockle
           command: |
             apk add --update curl
             VERSION=$(
                 curl --silent "https://api.github.com/repos/goodwithtech/dockle/releases/latest" | \
                 grep '"tag_name":' | \
                 sed -E 's/.*"v([^"]+)".*/\1/'
             )
             wget https://github.com/goodwithtech/dockle/releases/download/v${VERSION}/dockle_${VERSION}_Linux-64bit.tar.gz
             tar zxvf dockle_${VERSION}_Linux-64bit.tar.gz
             mv dockle /usr/local/bin
       - run:
           name: Scan the local image with dockle
           command: dockle --exit-code 1 dockle-ci-test:${CIRCLE_SHA1}
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:latest .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish-latest:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest
workflows:
  version: 2
  build-master:
    jobs:
      - dockle:
          filters:
            branches:
              only: main
      - build:
          filters:
            branches:
              only: main
      - publish-latest:
          requires:
            - build
          filters:
            branches:
              only: main


