version: 2.1

orbs:
  docker: circleci/docker@x.y.z

  lint:
    jobs:
      - docker/hadolint:
          dockerfiles: path/to/Dockerfile
          ignore-rules: 'DL4005,DL3008'
          trusted-registries: 'docker.io,my-company.com:5000'

  node: circleci/node@3.0.0
workflows:
  node-tests:
    jobs:
      - node/test
      - lint
